### ISSUE TITLE
Add more projects

### ISSUE THREAD

**Issue by Bhanu-code** [ianshulx/React-projects-for-beginners#1]
Hey, I want to add more projects for beginners to this repository. Please assign me with hactoberfest label if you want.

**Comment by ianshulx** [comment]
Okay, I assigning you, Please remember these things before your contribution.
1. Do not add any hard-level projects as you know it's a beginner-level project repo.
2. Focus on the quality of the projects, not the quantity.
3. make sure your project is error-free.
