### ISSUE TITLE
iNoteBook 

### ISSUE THREAD

**Issue by raj-mistry-01** [ianshulx/React-projects-for-beginners#109]
A minimalist web app that Saves the notes of user , updates and deleted 

Going to add flask backend with react front + back to download a specific note 

I hope you will assign this issue under hactoberfest tag.

Thanks , looking for further contribution to this repo.

**Comment by ianshulx** [comment]
@raj-mistry-01 Okay I've assigned you

**Comment by raj-mistry-01** [comment]
@ianshulx 

Thank you for assigning this issue to me .

As I will more possible **tomorrow** or max to max **the day after tomorrow** I will push the my mini project.

I ensure it will help.

Thank you.

**Comment by ianshulx** [comment]
@raj-mistry-01 Hi, are you working on this project??

**Comment by raj-mistry-01** [comment]
@ianshulx 
Yes today tonight I will push it , my exams are going on so that is why but tonight I will
