### ISSUE TITLE
Creating A NFTmarketplace using solidity , ether.js and react.js , including tailwindcss

### ISSUE THREAD

**Issue by TechnicallyKiller** [ianshulx/React-projects-for-beginners#111]

**Comment by ianshulx** [comment]
@TechnicallyKiller please list your project to project.js file with PR
example:
{
title: "React Todo App",
url: "https://github.com/ianshulx/React-projects-for-beginners/tree/main/react-todo-app",
description: "Start your coding journey with a beginner-friendly React Todo App, perfect for learning task management and basic web development",
imgSrc: "assets/todo.png"
},

**Comment by ianshulx** [comment]
@TechnicallyKiller hey are you working on this issue ?

**Comment by TechnicallyKiller** [comment]
yeahh am sorry for not being responsive!!

**Comment by ianshulx** [comment]
No problem @TechnicallyKiller
