### ISSUE TITLE
[Feature] Icons redirecting to the github repos

### ISSUE THREAD

**Issue by Durga-prasad-1** [ianshulx/React-projects-for-beginners#113]
@ianshulx  As you see the home page contains  the project links . Now when I click  on "Name the of the project " it is redirected to the git repos. I want to add a feature that is , when i click on the image of the project , it should redirect to the git repo

please assign this task to me!

**Comment by ianshulx** [comment]
@Durga-prasad-1 Thank you for finding this issue, I didn't even check it correctly, I'm assigning you for this issue

**Comment by Durga-prasad-1** [comment]
@ianshulx please assign the issue under hacktoberfest!

**Comment by ianshulx** [comment]
@Durga-prasad-1 Thank you!  I've merged your PR.
keep contributing to open-source.
