### ISSUE TITLE
List missing project to project.js file

### ISSUE THREAD

**Issue by ianshulx** [ianshulx/React-projects-for-beginners#115]
**Description:**

We need to update the `project.js` file to include a list of React projects, ensuring we have at least 35 projects listed. Currently, the repo has around 50 projects in the repository, so we need to add at least 15 more projects to reach this goal. Each project should be formatted as an object, with fields for the title, URL, description, and an image source for the icon.

Format example:
```js
{
    title: "React Todo App",
    url: "https://github.com/ianshulx/React-projects-for-beginners/tree/main/react-todo-app",
    description: "Start your coding journey with a beginner-friendly React Todo App, perfect for learning task management and basic web development.",
    imgSrc: "assets/todo.png"
}

**Comment by ianshulx** [comment]
@jks1111 okay, I've assigned you.

**Comment by Solomon-Dzokoto** [comment]
Please can you assign this issue to me too?

**Comment by ianshulx** [comment]
Hi @Solomon-Dzokoto I've assigned her already, You can check this out this issue https://github.com/ianshulx/Django-Projects-for-beginners/issues/34, this is the similar issue in another repo, reply on that issue I'll definitely assign you for that one.
You can point out few more issue in that repo if you really want to contribute in #Hacktoberfest, hope you get it 👍

**Comment by ianshulx** [comment]
Hi @jks1111, there's some issue with the icons you recently added can you please check this out?

**Comment by ianshulx** [comment]
@jks1111 no problem I've resolved the error.
