### ISSUE TITLE
Optimize Responsiveness of Index Page

### ISSUE THREAD

**Issue by ianshulx** [ianshulx/React-projects-for-beginners#118]
Page Link: https://anshulcodes.site/
File Link: [index.html](https://github.com/ianshulx/React-projects-for-beginners/blob/main/index.html)

The index page needs optimization for better responsiveness on various screen sizes. Implement media queries and ensure elements adjust smoothly across mobile, tablet, and desktop views.

**Comment by aniruddhaadak80** [comment]
I am working on this . Please assign me .

**Comment by aniruddhaadak80** [comment]
See #119 please .

**Comment by ianshulx** [comment]
@aniruddhaadak80 I've merged, thank you
