### ISSUE TITLE
Add Credit Card Validator

### ISSUE THREAD

**Issue by Anupam0-0** [ianshulx/React-projects-for-beginners#126]
Description:
 The program prompts the user to enter a number and determines whether it is a valid credit card number.
 
 Pls assign this to Hacktoberfest

**Comment by Krishnap2k4** [comment]
Hey @Anupam0-0 please assign this issue to me, I would love to work on this, Thank you!

**Comment by ShantannuDev2003** [comment]
Hey @Anupam0-0 ,please assign the task to develop the Credit Card Validator Program to me.I am  very glad to work on this, and I already have the code ready for it.Thank you!

**Comment by ianshulx** [comment]
@Anupam0-0 Hi!, I've assigned you fro this task.

**Comment by ianshulx** [comment]
@Krishnap2k4 @ShantannuDev2003 Hi! You’re welcome to add any project of your choice. Just submit a PR directly—no need to create a new issue. I’ll mark it with the Hacktoberfest label. Just go through the repo sizing guidelines and don’t forget to list your project along with its icon!
