### ISSUE TITLE
[UI] Change the background

### ISSUE THREAD

**Issue by aLok-1105** [ianshulx/React-projects-for-beginners#136]
What about this background ?

https://github.com/user-attachments/assets/7525d25d-26bd-4a19-aa21-24e95b4f8456

**Comment by aLok-1105** [comment]
@ianshulx , please assign me this issue if necessary or if changes are needed.

**Comment by ianshulx** [comment]
@ianshulx looks pretty good, I've assigned you 👍

**Comment by ianshulx** [comment]
@aLok-1105 hi can you pls recheck it, there's some issue in reflecting changes you made??

**Comment by aLok-1105** [comment]
@ianshulx Can you give more detail about the issue ?

**Comment by ianshulx** [comment]
@aLok-1105 sorry alok now page is working but when it was merged few changes weren't working, like bg wasn't changed and effect was working but at the end of page, not it's okay.

**Comment by aLok-1105** [comment]
@ianshulx Okay 👍🏻
