### ISSUE TITLE
Fix Index.html

### ISSUE THREAD

**Issue by isaurabhverma** [ianshulx/React-projects-for-beginners#16]

**Comment by Bhanu-code** [comment]
it is related to deployment. maintainer please check this out. I already updated index.html, not reflecting on the site but on the repository.

**Comment by ianshulx** [comment]
@isaurabhverma @Bhanu-code 
Okay fixed the index.html, now just need to update the list we'll update the list on every weekend of hacktoberfest, the reason is simple project list will be updating many time  and we can't update is every single time, so we'll be updating this on every weekend 👍👍
