### ISSUE TITLE
[feat]: Create a Color Palette generator.

### ISSUE THREAD

**Issue by purnasth** [ianshulx/React-projects-for-beginners#41]
## Prerequisites

- [x] vite + react
- [x] tailwindCSS

## Description
Create beautiful color palettes with the Color Palette Generator. Generate harmonious color schemes with a click and easily copy hex codes. A useful tool for designers and developers.

**Comment by ianshulx** [comment]
@purnasth pls update the index.html also

**Comment by purnasth** [comment]
Yes, I have also revised the index.html page, adding the github repository URL, a brief description, and a title. 

Attachments:

![image](https://github.com/ianshulx/React-projects-for-beginners/assets/107195487/6c130e6b-a7d9-41f1-9868-bf0198ec9dea)

**Comment by ianshulx** [comment]
@purnasth  okay
