### ISSUE TITLE
Missing Favicon in the website

### ISSUE THREAD

**Issue by rhnas110** [ianshulx/React-projects-for-beginners#43]
Hi Sir @ianshulx  
I'm new to open source contributions and I'd really want to contribute to your project! Please assign this issue to me, Thank you for your response Sir @ianshulx . I also participated in Hacktoberfest2023.

**Comment by ianshulx** [comment]
Okay I've assigned you

**Comment by ianshulx** [comment]
@rhnas110  thanks for fixing this issue, there's one more issue in this index.html, there are approximately 26 projects in the repo but the listed projects are only 18, can you please fix that issue, it'll add one more contribution to your hacktoberfest profile

**Comment by rhnas110** [comment]
Can I have a list of projects that have not been listed, Sir @ianshulx ? If I already have the list data, I will take care of this issue.
