### ISSUE TITLE
Blob Generator - CSS Blob Creation using ReactJS

### ISSUE THREAD

**Issue by ojasggg** [ianshulx/React-projects-for-beginners#49]
**Develop a Blob Generator App.**

**Description 📜**
A simple, minimalistic React Blob CSS code generator app.

**Requirements 🛠️**
The app, is going to have pleasing UI, with copy code to clipboard option, allow quick changes with Blob CSS code.

**Bonus ✨**
The app can have a various difficult CSS shape option in the near future.

⭐I would love to contribute the addition of this new mini-project to the React-projects-for-beginners repository.

**Comment by ianshulx** [comment]
@ojasggg you can add this

**Comment by ianshulx** [comment]
@ojasggg merged
