### ISSUE TITLE
What about logo in index.html? 

### ISSUE THREAD

**Issue by Bhanu-code** [ianshulx/React-projects-for-beginners#5]
What about the logo in index.html? Will maintainer create it or contributers can suggest.

**Comment by ianshulx** [comment]
Fix if want

**Comment by Rahulkottak** [comment]
Can I contribute in it too!?

**Comment by ianshulx** [comment]
@Rahulkottak  okay

**Comment by Bhanu-code** [comment]
I am getting merge conflicts for this, @Rahulkottak please add "./" before logo in banner of index.html and maintainer unassign me this issue.

**Comment by ianshulx** [comment]
fixed
