### ISSUE TITLE
feat: Sorting Algorithm Visualizer in react

### ISSUE THREAD

**Issue by ojasggg** [ianshulx/React-projects-for-beginners#51]
### **Description 📜**
This application has most of the sorting algorithm used in DSA and has visual representation of how these sorting algorithm works in background using clean UI in react. User can easily select different sorting algorithms, number of elements in an array and also can select the speed of sorting.

### **Requirements 🛠️**
The app, is going to have pleasing UI, with various sorting algorithm JS code. 

### **Bonus ✨**
Can add visualization of many other interesting algorithm in near future.

⭐I would love to contribute the addition of this new mini-react project to the this repository.

**Comment by ianshulx** [comment]
@ojasggg okay you can add this one

**Comment by ojasggg** [comment]
@ianshulx Can I contribute other remaining 2 contribution in this repo with some interesting react projects?

**Comment by ianshulx** [comment]
@ojasggg Absolutely you can, Please update index.html also, and check if all the projects in the repo match with index.html
