### ISSUE TITLE
feat: Full Stack Chat Application 

### ISSUE THREAD

**Issue by ojasggg** [ianshulx/React-projects-for-beginners#53]
**Description 📜**
This application will have entire chat functionality. Use of Tailwind CSS for designing frontend with node.js and express.js to handle the backend API. For real time data transfer Socket.io will also be used.

**Requirements 🛠️**
The app needs realtime data or chat transfer.
Functionality of sending friend request.

**Bonus ✨**
Can add media transfer in future by using Amazon S3 bucket for storing Images or any media.

⭐I would love to contribute the addition of this new mini-react project to the this repository.

**Comment by ianshulx** [comment]
@ojasggg This is beginner-friendly React JS repo, please add only Reeact based Front-end app

**Comment by ojasggg** [comment]
Got it, my bad.
