### ISSUE TITLE
feat: React Web3 theme Landing Page

### ISSUE THREAD

**Issue by ojasggg** [ianshulx/React-projects-for-beginners#54]
### React Web3 theme Landing Page

**Prerequisites**
- [x]  vite + react
- [x]  tailwindCSS or native CSS

**Description 📜**
Create Modern Landing page for companies related to Web3 theme. A useful design idea with modern and latest technology.

**Extra✨**
Can convert the entire design with developer personal need and requirements. Flexible with modern Tech Stack and design concepts. 

⭐Please assign this task to me.

**Comment by ianshulx** [comment]
@ojasggg I've assigned you to this task.

**Comment by ianshulx** [comment]
@ojasggg merged
