### ISSUE TITLE
feat: Text to Speech in React

### ISSUE THREAD

**Issue by ojasggg** [ianshulx/React-projects-for-beginners#57]
### Text to Speech in React

**Prerequisites**

- [x]  vite + react
- [x]  tailwindCSS or native CSS

**Description 📜**
Helpful application for developers or users who require their website to be accessibility for blind, deaf or even for normal users. Application have pleasing UI with various functions like sound, choice of voices and many more.

**Future Updates✨**

- Can include many more voices which users are comfortable with.
- Can create application give output in various languages.

⭐Please assign this task to me.

**Comment by ojasggg** [comment]
Thankyou so much @ianshulx  for letting me contribute in these many interesting react projects. I had a great time learning and contributing in opensource repository. I will keep on contributing if I found any other interesting react beginner projects. 

Thankyou again 😁 and happy coding 👍.

**Comment by ianshulx** [comment]
@ojasggg merged 👍, thank you for you contribution
