### ISSUE TITLE
Add Search functionality

### ISSUE THREAD

**Issue by Prriya-Karn** [ianshulx/React-projects-for-beginners#64]
1. Add search functionality in the top of the website. 
so that user can search the project and easily get those project.

2. add some effect in the website for attractive page

**Comment by Prriya-Karn** [comment]
@ianshulx please assign this issue to me

**Comment by ianshulx** [comment]
@Prriya-Karn I've assigned you, you can now work on this issue

**Comment by Prriya-Karn** [comment]
@ianshulx  I need some help, how to link App.jsx file with index.html my react code is not run could you please tell me how to solve this

**Comment by ianshulx** [comment]
@Prriya-Karn, I apologize, but I haven't encountered this issue before, so my knowledge on it is limited. I would recommend avoiding React for the index file; keeping it simple with JavaScript can suffice for implementing the search functionality. My aim is to maintain the repository's representation in a straightforward and accessible manner, hence this suggestion.
