### ISSUE TITLE
Optimize Project Listing Page

### ISSUE THREAD

**Issue by ianshulx** [ianshulx/React-projects-for-beginners#79]
# Project List Page Improvement

## Problem Statement

Our current Project List page is very simple and lacks a visually appealing design. We need to enhance this page to make it more user-friendly and aesthetically pleasing.

## Objective

The goal is to create a new Project List page with the following requirements:

1. **Single Page Implementation**: Everything should be on the same page to keep it simple and straightforward.
2. **Technologies**: The page should be developed using simple HTML, CSS, and JavaScript. This will ensure that new contributors can easily understand, modify, and improve the page in a short amount of time.
3. **Design**: I've added an image of the expected UI for the new Project List page. The current page is located [here](https://github.com/ianshulx/React-projects-for-beginners/blob/main/index.html).

## How to Contribute

If you’re interested in contributing to this project, please fork the repository, make your changes, and submit a pull request. Your contributions will be greatly appreciated!

### Expected UI Design

![Expected UI - Image 1](https://raw.githubusercontent.com/ianshulx/React-projects-for-beginners/main/temp/1.png)
![Expected UI - Image 2](https://raw.githubusercontent.com/ianshulx/React-projects-for-beginners/main/temp/2.png)

**Comment by mahato098** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by Akshaydotcom** [comment]
Hey! @ianshulx Can I work on this?

**Comment by ianshulx** [comment]
@Akshaydotcom Okay, I'm assigning you. Please note this point: "2. Technologies: The page should be developed using simple HTML, CSS, and JavaScript. This will ensure that new contributors can easily understand, modify, and improve the page in a short amount of time."

**Comment by ianshulx** [comment]
@Akshaydotcom One more request: Please activate GitHub Pages for this repository while working on this issue. This will create a live demo page that reflects changes in the index.html file. Not only will this help us identify the problem more effectively, but it will also add some creative flair to the page as we refine it.

**Comment by ianshulx** [comment]
@Akshaydotcom are you working on this issue?

**Comment by Akshaydotcom** [comment]
Hi @ianshulx , Yes I am working on this issue, I should be done by the end of the week,

**Comment by ianshulx** [comment]
@Akshaydotcom Thank you , I've merged the PR
