### ISSUE TITLE
Overall ui can be changed as well as the icons of all the projects must be changed

### ISSUE THREAD

**Issue by kanikaa-3018** [ianshulx/React-projects-for-beginners#82]
I want to contribute to this project for hacktoberfest2024, please assign this to me. I have noticed the following issues-

- ui can be improved( some better animation or gradient)
- icons for each object instead of react icon
- nav bar can be improved

**Comment by ianshulx** [comment]
@kanikaa-3018 okay I've assigned you for this issue, lease note this point: "2. Technologies: The page should be developed using simple HTML, CSS, and JavaScript. This will ensure that new contributors can easily understand, modify, and improve the page in a short amount of time."

**Comment by ianshulx** [comment]
### Expected UI Design

![Expected UI - Image 1](https://raw.githubusercontent.com/ianshulx/React-projects-for-beginners/main/temp/1.png)
![Expected UI - Image 2](https://raw.githubusercontent.com/ianshulx/React-projects-for-beginners/main/temp/2.png)
