### ISSUE TITLE
Easy to Add Projects In Repo

### ISSUE THREAD

**Issue by infinity-mayank** [ianshulx/React-projects-for-beginners#83]
- Update `index.html` to render the repeated divs of each project via script.
- Project contributors will only have to edit the array of data points of the project that they are adding.
- This will clean our `index.html` and make it shorter and more readable.

**Comment by infinity-mayank** [comment]
@ianshulx Please assign this to me. I can work on this.

**Comment by ianshulx** [comment]
Hi @infinity-mayank, thank you for your interest in contributing! I've already assigned a similar issue to another contributor. If they are unable to make the design visually appealing, I'll be sure to assign it to you. 

In the meantime, if you'd like to contribute, you're welcome to add more React projects to this repository. Additionally, I have another repository here: [Django Projects for Beginners](https://github.com/ianshulx/Django-Projects-for-beginners), where you could help by recreating the `index.html` file.

Looking forward to your contributions!

**Comment by infinity-mayank** [comment]
The issue I have raised is not regarding visual changes. It is for updating the structure of code and make it cleaner.

Please let me know if I can raise PR for review. I can make changes later when visual changes are done.

**Comment by ianshulx** [comment]
@infinity-mayank okay

**Comment by infinity-mayank** [comment]
@ianshulx Sorry, you have closed this issue. Can you please reopen and I can create the PR for it.

**Comment by infinity-mayank** [comment]
@ianshulx Hello, I can see that there are no open issue at this moment. Can I take this up? I will revamp project structure a little.

**Comment by ianshulx** [comment]
Sorry @infinity-mayank for the late reply. I've been busy with my schedule and didn't check my emails. I've assigned this to you.

**Comment by ianshulx** [comment]
@infinity-mayank merged ✅ thank for your contribution
