### ISSUE TITLE
Add Dictionary App

### ISSUE THREAD

**Issue by S-125** [ianshulx/React-projects-for-beginners#98]
@ianshulx  I want to contribute in this repository by adding a dictionary app using react.js . Please add hacktoberfest label and assign it to me.

**Comment by ianshulx** [comment]
list your project to project.js file
example:
{
title: "React Todo App",
url: "https://github.com/ianshulx/React-projects-for-beginners/tree/main/react-todo-app",
description: "Start your coding journey with a beginner-friendly React Todo App, perfect for learning task management and basic web development",
imgSrc: "assets/todo.png"
},
