### ISSUE TITLE
Project : Real Time chatting App - React , Socket , MongoDB

### ISSUE THREAD

**Issue by raj-mistry-01** [ianshulx/React-projects-for-beginners#99]
I hope you will assign this issue to me , As I will push my project to your repo and look  for further contribution to this repo.

**Comment by ianshulx** [comment]
@raj-mistry-01 I've assigned you for this task,
 Reminder: After contributing, kindly update the index.html file to reflect your project on the project showcase page. Also, don't forget to add a logo for your project to improve its visibility on the repository webpage. Thank you

**Comment by ianshulx** [comment]
add to project.js file
example:
{
title: "React Todo App",
url: "https://github.com/ianshulx/React-projects-for-beginners/tree/main/react-todo-app",
description: "Start your coding journey with a beginner-friendly React Todo App, perfect for learning task management and basic web development",
imgSrc: "assets/todo.png"
},

**Comment by raj-mistry-01** [comment]
@ianshulx 
Thank you for assigning this issue to me .

**Comment by ianshulx** [comment]
@raj-mistry-01 can you please list it project.js with a logo
